In [1]:
from IPython.display import Image
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')

### 새로운 칼럼 추가

In [3]:
df1 = df.copy()
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df1['VIP']=True
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,True
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,True

## 삭제
### 행(row) 삭제
행 삭제 시 index를 지정해 삭제

In [5]:
df1.drop(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,True
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,True

In [8]:
# 범위 지정
df1.drop(np.arange(10))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False,True
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,True

In [6]:
# fancy indexing
df1.drop([1, 3, 5, 7, 9])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,True
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,True

### 열 (column) 삭제
``axis=1`` 옵션 필수

In [7]:
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,True
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,True

In [8]:
df1.drop('class', axis=1).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,who,adult_male,deck,embark_town,alive,alone,VIP
0,0,3,male,22.0,1,0,7.2500,S,man,True,NaN,Southampton,no,False,True
1,1,1,female,38.0,1,0,71.2833,C,woman,False,C,Cherbourg,yes,False,True
2,1,3,female,26.0,0,0,7.9250,S,woman,False,NaN,Southampton,yes,True,True
3,1,1,female,35.0,1,0,53.1000,S,woman,False,C,Southampton,yes,False,True
4,0,3,male,35.0,0,0,8.0500,S,man,True,NaN,Southampton,no,True,True

In [9]:
df1.drop(['who', 'deck', 'alive'], axis=1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alone,VIP
0,0,3,male,22.0,1,0,7.2500,S,Third,True,Southampton,False,True
1,1,1,female,38.0,1,0,71.2833,C,First,False,Cherbourg,False,True
2,1,3,female,26.0,0,0,7.9250,S,Third,False,Southampton,True,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,Southampton,False,True
4,0,3,male,35.0,0,0,8.0500,S,Third,True,Southampton,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,True,Southampton,True,True
887,1,1,female,19.0,0,0,30.0000,S,First,False,Southampton,True,True
888,0,3,female,NaN,1,2,23.4500,S,Third,False,Southampton,False,True
889,1,1,male,26.0,0,0,30.0000,C,First,True,Cherbourg,True,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,True,Queenstown,True,True

``inplcae = True``삭제 내용을 바로 적용

In [10]:
df1.drop(['who', 'deck', 'alive'], axis=1, inplace=True)
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alone,VIP
0,0,3,male,22.0,1,0,7.2500,S,Third,True,Southampton,False,True
1,1,1,female,38.0,1,0,71.2833,C,First,False,Cherbourg,False,True
2,1,3,female,26.0,0,0,7.9250,S,Third,False,Southampton,True,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,Southampton,False,True
4,0,3,male,35.0,0,0,8.0500,S,Third,True,Southampton,True,True

### 컬럼간 연산

In [11]:
# family(가족) = sibsp 컬럼과 parch 컬럼의 합
df1 = df.copy()
df1['family'] = df1['sibsp'] + df1['parch']
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0

In [12]:
# 문자열의 합(이어붙히기)
df1['gender'] = df1['who'] + '-' + df1['sex']
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family,gender
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,man-male
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,woman-female
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,woman-female
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,woman-female
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,man-male

round() - 소수점 자릿수

In [13]:
df1['round'] = round(df1['fare'] / df1['age'], 2)
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family,gender,round
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,man-male,0.33
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,woman-female,1.88
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,woman-female,0.30
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,woman-female,1.52
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,man-male,0.23

NaN값을 1개라도 포함하고 있다면 결과는 **NaN**

In [14]:
df1.loc[df1['age'].isnull(), 'deck':].head()

   deck  embark_town alive  alone  family        gender  round
5   NaN   Queenstown    no   True       0      man-male    NaN
17  NaN  Southampton   yes   True       0      man-male    NaN
19  NaN    Cherbourg   yes   True       0  woman-female    NaN
26  NaN    Cherbourg    no   True       0      man-male    NaN
28  NaN   Queenstown   yes   True       0  woman-female    NaN

## datetime - 날짜, 시간
### date_range
- start : 시작날짜
- end : 끝날짜
- periods : 생성할 데이터 개수
- freq : 주기

In [15]:
dates = pd.date_range('20210101', periods=df.shape[0], freq='15H')
dates.shape

(891,)

In [16]:
df1 = df.copy()
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [17]:
df1['date'] = dates
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,date
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2021-01-01 00:00:00
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2021-01-01 15:00:00
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,2021-01-02 06:00:00
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2021-01-02 21:00:00
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,2021-01-03 12:00:00

In [18]:
# date 컬럼은 datetime64
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
 15  date         891 non-null    datetime64[ns]
dtypes: bool(2), category(2), datetime64[ns](1), float64(2), int64(4), object(5)
memory usage: 87.6+ KB

### datetime 타입
[document](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.year.html) \
``datetime``타입은 dt접근자로 아래의 날짜속성에 접근 가능
- pandas.Series.dt.year: 연도
- pandas.Series.dt.month: 월
- pandas.Series.dt.day: 일
- pandas.Series.dt.hour: 시
- pandas.Series.dt.minute: 분
- pandas.Series.dt.second: 초
- pandas.Series.dt.microsecond: micro 초
- pandas.Series.dt.nanosecond: nano 초
- pandas.Series.dt.week: 주
- pandas.Series.dt.weekofyear: 연중 몇 째주
- pandas.Series.dt.dayofweek: 요일 (월요일 0, 일요일 6)
- pandas.Series.dt.weekday: 요일 (dayofweek과 동일)
- pandas.Series.dt.dayofyear: 연중 몇 번째 날
- pandas.Series.dt.quarter: 분기

In [19]:
df1['date'].dt.year.tail()

886    2022
887    2022
888    2022
889    2022
890    2022
Name: date, dtype: int32

In [20]:
df1['date'].dt.dayofweek.head()

0    4
1    4
2    5
3    5
4    6
Name: date, dtype: int32

### to_datetime

In [21]:
df2 = pd.read_csv('data/seoul_bicycle.csv')
df2.head()

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,이용시간
0,Jan-20-2020,3,중랑센터,일일(회원),M,AGE_003,3,61.82,0.52,2230.0,75
1,Jan-20-2020,3,중랑센터,일일(회원),M,AGE_004,1,39.62,0.28,1220.0,15
2,Jan-20-2020,3,중랑센터,정기,M,AGE_005,3,430.85,4.01,17270.0,53
3,Jan-20-2020,5,상암센터 정비실,일일(회원),\N,AGE_005,2,1.79,0.02,90.0,33
4,Jan-20-2020,5,상암센터 정비실,정기,F,AGE_003,1,4501.96,45.47,196010.0,64

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327231 entries, 0 to 327230
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   대여일자    327231 non-null  object
 1   대여소번호   327231 non-null  int64
 2   대여소명    327231 non-null  object
 3   대여구분코드  327231 non-null  object
 4   성별      272841 non-null  object
 5   연령대코드   327231 non-null  object
 6   이용건수    327231 non-null  int64
 7   운동량     327231 non-null  object
 8   탄소량     327231 non-null  object
 9   이동거리    327231 non-null  float64
 10  이용시간    327231 non-null  int64
dtypes: float64(1), int64(3), object(7)
memory usage: 27.5+ MB

**대여일자** 컬럼은 object 타입이므로 ``datetime``타입으로 변경해야 .dt 접근자 사용 가능\
``pd.to_datetime()``: datetime type으로 변경

In [23]:
df2['대여일자'] = pd.to_datetime(df2['대여일자'])
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327231 entries, 0 to 327230
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   대여일자    327231 non-null  datetime64[ns]
 1   대여소번호   327231 non-null  int64
 2   대여소명    327231 non-null  object
 3   대여구분코드  327231 non-null  object
 4   성별      272841 non-null  object
 5   연령대코드   327231 non-null  object
 6   이용건수    327231 non-null  int64
 7   운동량     327231 non-null  object
 8   탄소량     327231 non-null  object
 9   이동거리    327231 non-null  float64
 10  이용시간    327231 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 27.5+ MB

In [24]:
df2['대여일자'].dt.year

0         2020
1         2020
2         2020
3         2020
4         2020
          ...
327226    2020
327227    2020
327228    2020
327229    2020
327230    2020
Name: 대여일자, Length: 327231, dtype: int32

### pd.to_numeric() - 수치형 변환
numerical type이 아닌 컬럼을 numerical(수치형) 컬럼으로 변환

In [25]:
df2.head()

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,이용시간
0,2020-01-20,3,중랑센터,일일(회원),M,AGE_003,3,61.82,0.52,2230.0,75
1,2020-01-20,3,중랑센터,일일(회원),M,AGE_004,1,39.62,0.28,1220.0,15
2,2020-01-20,3,중랑센터,정기,M,AGE_005,3,430.85,4.01,17270.0,53
3,2020-01-20,5,상암센터 정비실,일일(회원),\N,AGE_005,2,1.79,0.02,90.0,33
4,2020-01-20,5,상암센터 정비실,정기,F,AGE_003,1,4501.96,45.47,196010.0,64

In [26]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327231 entries, 0 to 327230
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   대여일자    327231 non-null  datetime64[ns]
 1   대여소번호   327231 non-null  int64
 2   대여소명    327231 non-null  object
 3   대여구분코드  327231 non-null  object
 4   성별      272841 non-null  object
 5   연령대코드   327231 non-null  object
 6   이용건수    327231 non-null  int64
 7   운동량     327231 non-null  object
 8   탄소량     327231 non-null  object
 9   이동거리    327231 non-null  float64
 10  이용시간    327231 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 27.5+ MB

운동량 컬럼은 수치형 컬럼으로 보이지만 object 타입임

In [27]:
pd.to_numeric(df2['운동량'])

ValueError: Unable to parse string "\N" at position 2344

In [28]:
# 2344 position에서 에러
df2.loc[2344]

대여일자      2020-01-20 00:00:00
대여소번호                     165
대여소명              165. 중앙근린공원
대여구분코드                 일일(회원)
성별                         \N
연령대코드                 AGE_003
이용건수                        1
운동량                        \N
탄소량                        \N
이동거리                      0.0
이용시간                       40
Name: 2344, dtype: object

운동량에 수치형이 아닌 개행 (\N)이 들어가 에러 발생 \
NaN값이나 숫자로 변환이 불가능한 문자열이 존재할 때 변환 실패\
``errors=`` 옵션값을 바꾸어 해결 가능\
``errors : {'ignore', 'raise', 'coerce'}, default 'raise'``

``errors='raise'``로 지정시 에러를 일으키며 코드를 중단 (기본값)

``errors='coerce'``로 지정시 잘못된 문자열은 NaN값으로 치환

In [29]:
pd.to_numeric(df2['운동량'], errors='coerce')

0           61.82
1           39.62
2          430.85
3            1.79
4         4501.96
           ...
327226     689.57
327227       0.00
327228      19.96
327229      43.77
327230    4735.63
Name: 운동량, Length: 327231, dtype: float64

In [30]:
pd.to_numeric(df2['운동량'], errors='coerce').loc[2344]

nan

``errors='ignore'``로 지정시 잘못된 문자열은 변환이 되지 않고 무시\
따라서 전체 컬럼의 dtype은 **object**로 남아있음

In [31]:
pd.to_numeric(df2['운동량'], errors='ignore')

0           61.82
1           39.62
2          430.85
3            1.79
4         4501.96
           ...
327226     689.57
327227          0
327228      19.96
327229      43.77
327230    4735.63
Name: 운동량, Length: 327231, dtype: object

In [32]:
pd.to_numeric(df2['운동량'], errors='ignore').loc[2344]

'\\N'

In [33]:
df2['운동량'] = pd.to_numeric(df2['운동량'], errors='coerce')

### pd.cut() - 구간 나누기(binning)
연속된 수치(continuous values)를 구간으로 나누어 카테고리화할 때 사용

In [34]:
df2.head()

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,이용시간
0,2020-01-20,3,중랑센터,일일(회원),M,AGE_003,3,61.82,0.52,2230.0,75
1,2020-01-20,3,중랑센터,일일(회원),M,AGE_004,1,39.62,0.28,1220.0,15
2,2020-01-20,3,중랑센터,정기,M,AGE_005,3,430.85,4.01,17270.0,53
3,2020-01-20,5,상암센터 정비실,일일(회원),\N,AGE_005,2,1.79,0.02,90.0,33
4,2020-01-20,5,상암센터 정비실,정기,F,AGE_003,1,4501.96,45.47,196010.0,64

In [35]:
# right=False로 지정시 우측 범위를 포함하지 않음
bins = [0, 200, 400, df2['운동량'].max()]
pd.cut(df2['운동량'], bins, right=False)

0                 [0.0, 200.0)
1                 [0.0, 200.0)
2         [400.0, 163936052.3)
3                 [0.0, 200.0)
4         [400.0, 163936052.3)
                  ...
327226    [400.0, 163936052.3)
327227            [0.0, 200.0)
327228            [0.0, 200.0)
327229            [0.0, 200.0)
327230    [400.0, 163936052.3)
Name: 운동량, Length: 327231, dtype: category
Categories (3, interval[float64, left]): [[0.0, 200.0) < [200.0, 400.0) < [400.0, 163936052.3)]

``labels``를 지정해줄 수 있으며, 지정한 bins의 개수보다 1개가 적어야 함

In [36]:
labels = ['운동부족', '보통', '많음']
pd.cut(df2['운동량'], bins, labels=labels, right=False)

0         운동부족
1         운동부족
2           많음
3         운동부족
4           많음
          ...
327226      많음
327227    운동부족
327228    운동부족
327229    운동부족
327230      많음
Name: 운동량, Length: 327231, dtype: category
Categories (3, object): ['운동부족' < '보통' < '많음']

In [37]:
df2.describe()

,대여일자,대여소번호,이용건수,운동량,이동거리,이용시간
count,327231,327231.000000,327231.000000,3.268300e+05,3.272310e+05,327231.000000
mean,2020-03-26 20:25:07.500206336,1288.411064,23.615400,6.921371e+03,1.068811e+05,752.814486
min,2020-01-20 00:00:00,3.000000,1.000000,0.000000e+00,0.000000e+00,0.000000
25%,2020-02-20 00:00:00,562.000000,2.000000,1.380500e+02,5.290000e+03,66.000000
50%,2020-03-20 00:00:00,1204.000000,6.000000,6.017050e+02,2.290000e+04,207.000000
75%,2020-04-20 00:00:00,1933.000000,22.000000,2.481175e+03,9.346000e+04,670.000000
max,2020-05-20 00:00:00,99999.000000,7451.000000,1.639361e+08,5.670905e+07,458960.000000
std,NaN,1012.645329,59.922618,6.564823e+05,4.634955e+05,2647.383179

``bins`` 옵션에 나누고자 하는 구간의 개수를 설정

In [42]:
df2['운동량_cut'] = pd.cut(df2['운동량'], bins=10)

TypeError: putmask: first argument must be an array

In [54]:
df2['운동량_cut'].value_counts()

KeyError: '운동량_cut'