In [1]:
from IPython.display import Image
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## apply() - 함수 적용

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

### 함수 (function) 정의

In [5]:
def tranform_who(x):
    if x == 'man' :
        return '남자'
    elif x == 'woman':
        return '여자'
    else:
        return '아이'

In [6]:
df['who'].apply(tranform_who)

0      남자
1      여자
2      여자
3      여자
4      남자
       ..
886    남자
887    여자
888    여자
889    남자
890    남자
Name: who, Length: 891, dtype: object

In [7]:
df['who'].apply(tranform_who).value_counts()

who
남자    537
여자    271
아이     83
Name: count, dtype: int64

In [8]:
def tranform_who(x):
    return x['fare'] / x['age']

In [9]:
df.apply(tranform_who, axis=1)

0      0.329545
1      1.875876
2      0.304808
3      1.517143
4      0.230000
         ...
886    0.481481
887    1.578947
888         NaN
889    1.153846
890    0.242188
Length: 891, dtype: float64

## apply() - lambda 함수

In [10]:
df['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [12]:
df['survived'].apply(lambda x : '생존' if x == 1 else '사망').value_counts()

survived
사망    549
생존    342
Name: count, dtype: int64

## groupbt() - 그룹

In [13]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [14]:
df.groupby('sex').mean(numeric_only=True)

,survived,pclass,age,sibsp,parch,fare,adult_male,alone
sex,,,,,,,,
female,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818,0.000000,0.401274
male,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893,0.930676,0.712305

### 2개 이상의 컬럼으로 그룹
list로 묶어서 지정

In [15]:
df.groupby(['sex', 'pclass']).mean(numeric_only=True)

               survived        age     sibsp     parch        fare  \
sex    pclass
female 1       0.968085  34.611765  0.553191  0.457447  106.125798
       2       0.921053  28.722973  0.486842  0.605263   21.970121
       3       0.500000  21.750000  0.895833  0.798611   16.118810
male   1       0.368852  41.281386  0.311475  0.278689   67.226127
       2       0.157407  30.740707  0.342593  0.222222   19.741782
       3       0.135447  26.507589  0.498559  0.224784   12.661633

               adult_male     alone
sex    pclass
female 1         0.000000  0.361702
       2         0.000000  0.421053
       3         0.000000  0.416667
male   1         0.975410  0.614754
       2         0.916667  0.666667
       3         0.919308  0.760807

### 1개의 특정 컬럼에 대한 결과 도출

In [16]:
df.groupby(['sex', 'pclass'])['survived'].mean(numeric_only=True)

sex     pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: survived, dtype: float64

``pd.DataFrame()``, ``survived``컬럼을 ``[]``으로 한번더 감싸주는 방법

In [17]:
pd.DataFrame(df.groupby(['sex', 'pclass'])['survived'].mean(numeric_only=True))

               survived
sex    pclass
female 1       0.968085
       2       0.921053
       3       0.500000
male   1       0.368852
       2       0.157407
       3       0.135447

In [18]:
df.groupby(['sex', 'pclass'])[['survived']].mean(numeric_only=True)

               survived
sex    pclass
female 1       0.968085
       2       0.921053
       3       0.500000
male   1       0.368852
       2       0.157407
       3       0.135447

### reset_index() : 인덱스 초기화
그룹핑된 데이터프레임의 index를 초기화하여 새로운 데이터프레임 생성

In [19]:
df.groupby(['sex', 'pclass'])['survived'].mean(numeric_only=True).reset_index()

      sex  pclass  survived
0  female       1  0.968085
1  female       2  0.921053
2  female       3  0.500000
3    male       1  0.368852
4    male       2  0.157407
5    male       3  0.135447

### 다중 컬럼에 대한 결과도출

In [20]:
df.groupby(['sex', 'pclass'])[['survived', 'age']].mean(numeric_only = True)

               survived        age
sex    pclass
female 1       0.968085  34.611765
       2       0.921053  28.722973
       3       0.500000  21.750000
male   1       0.368852  41.281386
       2       0.157407  30.740707
       3       0.135447  26.507589

### 다중 통계 함수 적용
여러가지의 통계값을 적용할 때는 ``agg()``를 사용

In [21]:
df.groupby(['sex', 'pclass'])[['survived', 'age']].agg(['mean', 'sum', 'max', 'min'])

               survived                    age
                   mean sum max min       mean      sum   max   min
sex    pclass
female 1       0.968085  91   1   0  34.611765  2942.00  63.0  2.00
       2       0.921053  70   1   0  28.722973  2125.50  57.0  2.00
       3       0.500000  72   1   0  21.750000  2218.50  63.0  0.75
male   1       0.368852  45   1   0  41.281386  4169.42  80.0  0.92
       2       0.157407  17   1   0  30.740707  3043.33  70.0  0.67
       3       0.135447  47   1   0  26.507589  6706.42  74.0  0.42

### pivot_table()
``index``, ``columns``, ``values``를 지정해 피벗

### 1개의 그룹에 대한 단일 컬럼 결과

In [25]:
df.pivot_table(index='who', values='survived')

       survived
who
child  0.590361
man    0.163873
woman  0.756458

In [26]:
df.pivot_table(columns='who', values='survived')

who          child       man     woman
survived  0.590361  0.163873  0.756458

### 다중 그룹에 대한 단일 컬럼 결과

In [27]:
df.pivot_table(index=['who', 'pclass'], values='survived')

              survived
who   pclass
child 1       0.833333
      2       1.000000
      3       0.431034
man   1       0.352941
      2       0.080808
      3       0.119122
woman 1       0.978022
      2       0.909091
      3       0.491228

### index에 컬럼을 중첩하지 않고 행과 열로 펼친 결과

In [28]:
df.pivot_table(index='who', columns='pclass', values='survived')

pclass         1         2         3
who
child   0.833333  1.000000  0.431034
man     0.352941  0.080808  0.119122
woman   0.978022  0.909091  0.491228

### 다중 통계함수 적용

In [29]:
df.pivot_table(index='who', columns='pclass', values='survived', aggfunc=['sum', 'mean'])

       sum              mean
pclass   1   2   3         1         2         3
who
child    5  19  25  0.833333  1.000000  0.431034
man     42   8  38  0.352941  0.080808  0.119122
woman   89  60  56  0.978022  0.909091  0.491228