In [1]:
from IPython.display import Image
import numpy as np
import pandas as pd
import seaborn as sns

In [6]:
# 1월~6월 상반기 데이터
gas1 = pd.read_csv('data/gas_first_2019.csv', encoding='euc-kr')

In [3]:
print(gas1.shape)
gas1.head()

(90590, 11)

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190101,SK에너지,셀프,1673,1465,1365,0
1,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190102,SK에너지,셀프,1673,1465,1365,0
2,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190103,SK에너지,셀프,1673,1465,1365,0
3,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190104,SK에너지,셀프,1673,1465,1365,0
4,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190105,SK에너지,셀프,1673,1465,1365,0

In [7]:
# 7월~12월 하반기 데이터
gas2 = pd.read_csv('data/gas_second_2019.csv', encoding='euc-kr')

In [5]:
print(gas2.shape)
gas2.head()

(91124, 11)

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190701,SK에너지,셀프,1777,1577,1477,0
1,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190702,SK에너지,셀프,1777,1577,1477,0
2,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190703,SK에너지,셀프,1777,1577,1477,0
3,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190704,SK에너지,셀프,1777,1577,1477,0
4,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190705,SK에너지,셀프,1777,1577,1477,0

### concat() - 데이터 연결

#### 행 방향으로 연결
기본 값 ``axis=0``
같은 column끼리 데이터 연결

In [8]:
pd.concat([gas1, gas2])

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190101,SK에너지,셀프,1673,1465,1365,0
1,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190102,SK에너지,셀프,1673,1465,1365,0
2,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190103,SK에너지,셀프,1673,1465,1365,0
3,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190104,SK에너지,셀프,1673,1465,1365,0
4,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190105,SK에너지,셀프,1673,1465,1365,0
...,...,...,...,...,...,...,...,...,...,...,...
91119,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191227,GS칼텍스,셀프,0,1540,1389,1100
91120,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191228,GS칼텍스,셀프,0,1540,1389,1100
91121,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191229,GS칼텍스,셀프,0,1540,1389,1100
91122,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191230,GS칼텍스,셀프,0,1540,1389,1100
91123,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191231,GS칼텍스,셀프,0,1540,1389,1100

index가 초기화되지 않아 전체 DataFrame의 개수와 index가 동일 X

In [12]:
gas = pd.concat([gas1, gas2], ignore_index = True)
gas

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190101,SK에너지,셀프,1673,1465,1365,0
1,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190102,SK에너지,셀프,1673,1465,1365,0
2,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190103,SK에너지,셀프,1673,1465,1365,0
3,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190104,SK에너지,셀프,1673,1465,1365,0
4,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190105,SK에너지,셀프,1673,1465,1365,0
...,...,...,...,...,...,...,...,...,...,...,...
181709,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191227,GS칼텍스,셀프,0,1540,1389,1100
181710,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191228,GS칼텍스,셀프,0,1540,1389,1100
181711,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191229,GS칼텍스,셀프,0,1540,1389,1100
181712,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191230,GS칼텍스,셀프,0,1540,1389,1100
181713,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191231,GS칼텍스,셀프,0,1540,1389,1100

#### 열 방향으로 연결
``axis = 1`` 지정필요

In [13]:
gas1 = gas.iloc[:, :5]
gas2 = gas.iloc[:, 5:]

In [14]:
gas1.head()

         번호      지역            상호              주소        기간
0  A0006039  서울 강남구  (주)동하힐탑셀프주유소  서울 강남구 논현로 640  20190101
1  A0006039  서울 강남구  (주)동하힐탑셀프주유소  서울 강남구 논현로 640  20190102
2  A0006039  서울 강남구  (주)동하힐탑셀프주유소  서울 강남구 논현로 640  20190103
3  A0006039  서울 강남구  (주)동하힐탑셀프주유소  서울 강남구 논현로 640  20190104
4  A0006039  서울 강남구  (주)동하힐탑셀프주유소  서울 강남구 논현로 640  20190105

In [15]:
gas2.head()

      상표 셀프여부  고급휘발유   휘발유    경유  실내등유
0  SK에너지   셀프   1673  1465  1365     0
1  SK에너지   셀프   1673  1465  1365     0
2  SK에너지   셀프   1673  1465  1365     0
3  SK에너지   셀프   1673  1465  1365     0
4  SK에너지   셀프   1673  1465  1365     0

In [16]:
pd.concat([gas1, gas2], axis=1)

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190101,SK에너지,셀프,1673,1465,1365,0
1,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190102,SK에너지,셀프,1673,1465,1365,0
2,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190103,SK에너지,셀프,1673,1465,1365,0
3,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190104,SK에너지,셀프,1673,1465,1365,0
4,A0006039,서울 강남구,(주)동하힐탑셀프주유소,서울 강남구 논현로 640,20190105,SK에너지,셀프,1673,1465,1365,0
...,...,...,...,...,...,...,...,...,...,...,...
181709,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191227,GS칼텍스,셀프,0,1540,1389,1100
181710,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191228,GS칼텍스,셀프,0,1540,1389,1100
181711,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191229,GS칼텍스,셀프,0,1540,1389,1100
181712,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191230,GS칼텍스,셀프,0,1540,1389,1100
181713,A0032659,서울 중랑구,지에스칼텍스㈜ 소망주유소,서울 중랑구 망우로 475,20191231,GS칼텍스,셀프,0,1540,1389,1100

### merge() - 병합
공통된 key값(컬럼)을 가지고 있을 시 병합 가능

In [17]:
df1 = pd.DataFrame({
    '고객명': ['박세리', '이대호', '손흥민', '김연아', '마이클조던'],
    '생년월일': ['1980-01-02', '1982-02-22', '1993-06-12', '1988-10-16', '1970-03-03'],
    '성별': ['여자', '남자', '남자', '여자', '남자']})
df1

     고객명        생년월일  성별
0    박세리  1980-01-02  여자
1    이대호  1982-02-22  남자
2    손흥민  1993-06-12  남자
3    김연아  1988-10-16  여자
4  마이클조던  1970-03-03  남자

In [18]:
df2 = pd.DataFrame({
    '고객명': ['김연아', '박세리', '손흥민', '이대호', '타이거우즈'],
    '연봉': ['2000원', '3000원', '1500원', '2500원', '3500원']})
df2

     고객명     연봉
0    김연아  2000원
1    박세리  3000원
2    손흥민  1500원
3    이대호  2500원
4  타이거우즈  3500원

### 병합하는 방법 4가지
``how``옵션값을 지정해 4가지 방식으로 병합 가능
- how : {``left``, ``right``, ``outer``, ``inner``}
- dafault값 : ``inner``

In [20]:
# how='inner' (default)
pd.merge(df1, df2)

   고객명        생년월일  성별     연봉
0  박세리  1980-01-02  여자  3000원
1  이대호  1982-02-22  남자  2500원
2  손흥민  1993-06-12  남자  1500원
3  김연아  1988-10-16  여자  2000원

In [21]:
pd.merge(df1, df2, how='left')

     고객명        생년월일  성별     연봉
0    박세리  1980-01-02  여자  3000원
1    이대호  1982-02-22  남자  2500원
2    손흥민  1993-06-12  남자  1500원
3    김연아  1988-10-16  여자  2000원
4  마이클조던  1970-03-03  남자    NaN

In [22]:
pd.merge(df1, df2, how='right')

     고객명        생년월일   성별     연봉
0    김연아  1988-10-16   여자  2000원
1    박세리  1980-01-02   여자  3000원
2    손흥민  1993-06-12   남자  1500원
3    이대호  1982-02-22   남자  2500원
4  타이거우즈         NaN  NaN  3500원

In [23]:
pd.merge(df1, df2, how='outer')

     고객명        생년월일   성별     연봉
0    박세리  1980-01-02   여자  3000원
1    이대호  1982-02-22   남자  2500원
2    손흥민  1993-06-12   남자  1500원
3    김연아  1988-10-16   여자  2000원
4  마이클조던  1970-03-03   남자    NaN
5  타이거우즈         NaN  NaN  3500원

### 병합하려는 컬럼의 이름이 다른 경우

In [24]:
df1 = pd.DataFrame({
    '이름': ['박세리', '이대호', '손흥민', '김연아', '마이클조던'],
    '생년월일': ['1980-01-02', '1982-02-22', '1993-06-12', '1988-10-16', '1970-03-03'],
    '성별': ['여자', '남자', '남자', '여자', '남자']})
df1

      이름        생년월일  성별
0    박세리  1980-01-02  여자
1    이대호  1982-02-22  남자
2    손흥민  1993-06-12  남자
3    김연아  1988-10-16  여자
4  마이클조던  1970-03-03  남자

In [25]:
df2 = pd.DataFrame({
    '고객명': ['김연아', '박세리', '손흥민', '이대호', '타이거우즈'],
    '연봉': ['2000원', '3000원', '1500원', '2500원', '3500원']})
df2

     고객명     연봉
0    김연아  2000원
1    박세리  3000원
2    손흥민  1500원
3    이대호  2500원
4  타이거우즈  3500원

In [27]:
pd.merge(df1, df2, left_on='이름', right_on='고객명')

    이름        생년월일  성별  고객명     연봉
0  박세리  1980-01-02  여자  박세리  3000원
1  이대호  1982-02-22  남자  이대호  2500원
2  손흥민  1993-06-12  남자  손흥민  1500원
3  김연아  1988-10-16  여자  김연아  2000원